# Generated by Django 5.2.3 on 2025-06-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='Cars_table',
        ),
    ]
